### ISSUE TITLE
Just wanted to say thank you

### ISSUE THREAD

**Issue by artembunichev** [lucas-mior/clipsim#3]
Thank you very much for creating this project! I've just tried it and it seems to be working like a charm!

Offtop: I really want to understand Xlib and I hope that your source will help me a lot, so thank you twice :) Especially I want to know, how did you implement saving selection after owner window closes? I will try to explore the source, but could you please explain me in very simple terms the main idea and its implementation in Xlib?

**Comment by lucas-mior** [comment]
You're welcome :).
Everything related to Xlib is in `clipboard.c`.

**Comment by artembunichev** [comment]
Thank you for the reply!
Do I understand the idea correctly (in very simple words, how do I roughly imagine this): in the daemon mode, our program sits in the background and waits some window will get a clipboard selection. So, when user presses ctrl+c, the active window will own a clipboard selection, and our program will read it from then owner window (only read, not make itself a selection owner) and save it to internal storage. Now, we have 2 possible scenarios: 1) the owner is alive; user requests a clipboard selection pressing ctrl+v; as far as selection's owner is still exists, user will get selection response from it and our program is actually do nothing in this case (but it still stores a selection copy); 2) the owner window was closed; our program will know that by 'selection lost' event (it may happen only if owner window dies) and now it will make a simple background window (or it may create it in the very begining) and say to x server that now this window owns a clipboard selection and put the previously saved selection in it; now, when user presses ctrl+v and requests a clipboard selection, he will get it from our program's background window.
Phew, hope my thoughts are clear :)

**Comment by lucas-mior** [comment]
That not entirely correct. I don't actually use a window to own the selection that was recovered. Instead, I copy it back using `xclip`, which was easier to implement. I only use a dummy window to watch the X selection events. The advantage of using `xclip` over implementing a selection owner is that the former is a mature solution, that also works for images. I don't know if implementing all that logic in `clipsim` would be worth it, I think not.

**Comment by artembunichev** [comment]
Finally I've made my own simple clipboard manager for X11. Your project and its source code are great and they helped me to figure out how Xlib actually works. Your personal explanation I asked you for in this issue also shed some light on it, thank you! So I want to share my program with you, hope you enjoy it: https://github.com/artembunichev/xsd.
