### ISSUE TITLE
Clipsim doesn't work on startup

### ISSUE THREAD

**Issue by Letus252** [lucas-mior/clipsim#4]
I made Clipsim into a systemctl service so it can run on startup. Despite this, it fails to start the daemon unless I manually do it. I didn't specify environment variables because I don't care about clipboard history, and I'm not sure if I know how to recompile it. I only need the clipboard history to persist after closing a given program (in fact, I prefer not to have clipboard history). Could you help me make it work on startup?

(Linux arch kde 6 plasma)

[f0x@archlinux ~]$ systemctl --user status clipsim.service
○ clipsim.service - Clipboard manager (https://github.com/lucas-mior/clipsim)
     Loaded: loaded (/home/f0x/.config/systemd/user/clipsim.service; enabled; preset: enabled
)
     Active: inactive (dead) since Sun 2024-04-28 13:41:54 CEST; 10min ago
   Duration: 64ms
   Main PID: 480 (code=exited, status=1/FAILURE)
        CPU: 14ms

Apr 28 13:41:54 archlinux systemd[471]: Started Clipboard manager (https://github.com/lucas-mior/clipsim).
Apr 28 13:41:54 archlinux systemd[471]: clipsim.service: Main process exited, code=exited, status=1/FAILURE
Apr 28 13:41:54 archlinux systemd[471]: clipsim.service: Failed with result 'exit-code'.
[f0x@archlinux ~]$ systemctl --user stop clipsim.service
[f0x@archlinux ~]$ ps aux | grep clipsim
f0x         3231  0.0  0.0   6572  4204 pts/2    S+   13:54   0:00 grep --color=auto clipsim
[f0x@archlinux ~]$ systemctl --user start clipsim.service
[f0x@archlinux ~]$ systemctl --user status clipsim.service
● clipsim.service - Clipboard manager (https://github.com/lucas-mior/clipsim)
     Loaded: loaded (/home/f0x/.config/systemd/user/clipsim.service; enabled; preset: enabled
)
     Active: active (running) since Sun 2024-04-28 13:54:13 CEST; 3s ago
   Main PID: 3241 (clipsim)
      Tasks: 2 (limit: 19072)
     Memory: 8.6M (peak: 8.9M)
        CPU: 35ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/clipsim.service
             └─3241 /sbin/clipsim --daemon

Apr 28 13:54:13 archlinux systemd[471]: Started Clipboard manager (https://github.com/lucas-mior/clipsim).
Apr 28 13:54:13 archlinux clipsim[3241]: Error opening history file for reading: No such file or directory
Apr 28 13:54:13 archlinux clipsim[3241]: History will start empty.
Apr 28 13:54:13 archlinux clipsim[3241]: CLIPSIM_SIGNAL_PROGRAM is not defined.
Apr 28 13:54:13 archlinux clipsim[3241]: CLIPSIM_SIGNAL_NUMBER is not defined.
[f0x@archlinux ~]$

**Comment by lucas-mior** [comment]
I suggest you start clipsim in your `.xinitrc`or equivalent. But I can take a look into it.

**Comment by Letus252** [comment]
Thanks for the answer. I new to linux so I'm not sure how to exactly do it. I tired adding:

export XDG_CACHE_HOME=$HOME/.cache
clipsim --daemon &

(also without to #!/bin/sh) to .xinitrc file but it didn't work. (Maybe because I'm using display manger Ly?).

**Comment by lucas-mior** [comment]
You should check the documentation for your display manager and desktop environment. There you will find how to autostart X programs.

**Comment by Letus252** [comment]
Hey, I solved this issue and wanted to follow up in case someone is in a similar situation.
Since I'm using KDE, the only thing I had to do was add this simple script to the Autostart directory:

#!/bin/sh

export XDG_CACHE_HOME=$HOME/.cache
clipsim --daemon &

Make sure to 'chmod +x ' it first, and it should work. Thank you @lucas-mior for help.
